// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0fy0_6Q4vWB87NkY8MP8H-uuzwUnRtA',
    appId: '1:937750694738:android:f94acc825a81bd0f83088b',
    messagingSenderId: '937750694738',
    projectId: 'emotioncare-cea39',
    storageBucket: 'emotioncare-cea39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNSObGgq0QyGesCDsw_UT01uzstSHtd4',
    appId: '1:937750694738:ios:eae57e488b5d231e83088b',
    messagingSenderId: '937750694738',
    projectId: 'emotioncare-cea39',
    storageBucket: 'emotioncare-cea39.firebasestorage.app',
    iosBundleId: 'com.example.emotioncare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqQVpOVpppOm2XoY10GxUHElgwZtZHNYs',
    appId: '1:937750694738:web:24d7f66d6070bca183088b',
    messagingSenderId: '937750694738',
    projectId: 'emotioncare-cea39',
    authDomain: 'emotioncare-cea39.firebaseapp.com',
    storageBucket: 'emotioncare-cea39.firebasestorage.app',
    measurementId: 'G-DT6HY93WVE',
  );

}